# =========================================================
# ApexDeploy - Docker Builder
# Gemini-powered Dockerfile generation and Docker image building
# =========================================================

import json
import logging
import re
from pathlib import Path
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from src.config.settings import settings
from src.core.exceptions import DockerException
from src.docker.docker_client import get_client, is_docker_available
from src.llm.gemini_client import generate_structured_json
from src.llm.prompts import DOCKER_SYSTEM_INSTRUCTION, DOCKER_GEN_USER_PROMPT

logger = logging.getLogger("docker.builder")


# ---- Pydantic Response Schemas for Gemini ----

class DockerfileResult(BaseModel):
    """Structured Gemini response containing generated Dockerfile and docker-compose content."""
    dockerfile_content: str = Field(
        description="Complete Dockerfile content with multi-stage build, optimized layers, and security best practices."
    )
    compose_content: str = Field(
        description="Complete docker-compose.yml content exposing the application with health checks."
    )
    base_image: str = Field(
        default="python:3.12-slim",
        description="The base Docker image used in the Dockerfile."
    )
    exposed_port: int = Field(
        default=8000,
        description="The primary port the application exposes inside the container."
    )
    entrypoint_command: str = Field(
        default="",
        description="The CMD or ENTRYPOINT used to start the application."
    )
    optimization_notes: List[str] = Field(
        default_factory=list,
        description="List of optimization decisions made in the Dockerfile generation."
    )


class BuildResult(BaseModel):
    """Result of a Docker image build operation."""
    success: bool = Field(description="Whether the build completed successfully.")
    image_id: str = Field(default="", description="SHA256 image ID of the built image.")
    image_name: str = Field(default="", description="Full image name with tag.")
    image_tag: str = Field(default="latest", description="Image tag.")
    size_bytes: int = Field(default=0, description="Image size in bytes.")
    build_logs: List[str] = Field(default_factory=list, description="Build output log lines.")
    error_message: str = Field(default="", description="Error details if build failed.")


# ---- Fallback Dockerfile Templates ----

FALLBACK_DOCKERFILES: Dict[str, str] = {
    "python": """# Auto-generated by ApexDeploy
FROM python:3.12-slim AS builder

WORKDIR /app

# Install dependencies first for layer caching
COPY requirements.txt .
RUN pip install --no-cache-dir --user -r requirements.txt

# Production stage
FROM python:3.12-slim

WORKDIR /app

# Copy installed packages from builder
COPY --from=builder /root/.local /root/.local
ENV PATH=/root/.local/bin:$PATH

# Copy application source
COPY . .

# Security: run as non-root user
RUN useradd --create-home appuser
USER appuser

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\
    CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/health')" || exit 1

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
""",
    "javascript": """# Auto-generated by ApexDeploy
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY . .

RUN addgroup -g 1001 -S appgroup && adduser -S appuser -G appgroup
USER appuser

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\
    CMD wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1

CMD ["node", "index.js"]
""",
    "java": """# Auto-generated by ApexDeploy
FROM maven:3.9-eclipse-temurin-21-alpine AS builder

WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn package -DskipTests -B

FROM eclipse-temurin:21-jre-alpine

WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar

RUN addgroup -g 1001 -S appgroup && adduser -S appuser -G appgroup
USER appuser

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=10s --start-period=15s --retries=3 \\
    CMD wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1

CMD ["java", "-jar", "app.jar"]
""",
}

FALLBACK_COMPOSE = """# Auto-generated by ApexDeploy
version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: {image_name}:{image_tag}
    container_name: {container_name}
    ports:
      - "{host_port}:{container_port}"
    environment:
      - APP_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "echo healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - apexdeploy-network

networks:
  apexdeploy-network:
    driver: bridge
"""


# ---- Public API ----

async def generate_dockerfile(
    language: str,
    files_list: List[str],
    dependency_content: str = "",
) -> DockerfileResult:
    """Generates a Dockerfile and docker-compose.yml using Gemini LLM.

    Falls back to language-specific templates if Gemini is unavailable or fails.

    Args:
        language: Detected programming language (python, javascript, java, etc.).
        files_list: List of source file paths in the repository.
        dependency_content: Content of the dependency file (requirements.txt, package.json).

    Returns:
        DockerfileResult with generated Dockerfile and docker-compose content.
    """
    logger.info(f"Generating Dockerfile for {language} project ({len(files_list)} files)")

    # Truncate file list for token efficiency
    truncated_files = files_list[:50]
    files_str = "\n".join(truncated_files)
    if len(files_list) > 50:
        files_str += f"\n... and {len(files_list) - 50} more files"

    # Truncate dependency content
    dep_content = dependency_content[:3000] if dependency_content else "No dependency file found."

    user_prompt = DOCKER_GEN_USER_PROMPT.format(
        language=language,
        files_list=files_str,
        dependency_file_content=dep_content,
    )

    try:
        raw_result = await generate_structured_json(
            prompt=user_prompt,
            response_schema=DockerfileResult,
            system_instruction=DOCKER_SYSTEM_INSTRUCTION,
        )

        result = DockerfileResult(**raw_result)

        # Validate that Gemini returned non-empty content
        if not result.dockerfile_content or len(result.dockerfile_content.strip()) < 20:
            logger.warning("Gemini returned empty/invalid Dockerfile. Using fallback template.")
            return _get_fallback_dockerfile(language)

        logger.info(
            f"Gemini generated Dockerfile (base: {result.base_image}, port: {result.exposed_port})"
        )
        return result

    except Exception as e:
        logger.warning(f"Gemini Dockerfile generation failed: {e}. Using fallback template.")
        return _get_fallback_dockerfile(language)


def _get_fallback_dockerfile(language: str) -> DockerfileResult:
    """Returns a pre-built Dockerfile template for the given language."""
    lang_key = language.lower()
    if lang_key in ("typescript", "tsx", "jsx"):
        lang_key = "javascript"
    elif lang_key in ("cpp", "c", "csharp", "go", "rust", "ruby", "php"):
        lang_key = "python"  # Default fallback

    dockerfile = FALLBACK_DOCKERFILES.get(lang_key, FALLBACK_DOCKERFILES["python"])

    # Determine port from template
    port = 8000
    if lang_key == "javascript":
        port = 3000
    elif lang_key == "java":
        port = 8080

    return DockerfileResult(
        dockerfile_content=dockerfile,
        compose_content=FALLBACK_COMPOSE.format(
            image_name="apexdeploy/app",
            image_tag="latest",
            container_name="apexdeploy-app",
            host_port=port,
            container_port=port,
        ),
        base_image="python:3.12-slim" if lang_key == "python" else f"{lang_key}-base",
        exposed_port=port,
        entrypoint_command="auto-detected",
        optimization_notes=["Used fallback template (Gemini unavailable)"],
    )


def build_image(
    build_path: str,
    image_name: str,
    image_tag: str = "latest",
    dockerfile_path: str = "Dockerfile",
) -> BuildResult:
    """Builds a Docker image from the specified build context directory.

    Args:
        build_path: Absolute path to the build context (directory containing Dockerfile).
        image_name: Name for the built image (e.g., 'apexdeploy/my-app').
        image_tag: Tag for the image (default: 'latest').
        dockerfile_path: Relative path to the Dockerfile within build_path.

    Returns:
        BuildResult with image metadata and build logs.

    Raises:
        DockerException: If Docker is unavailable or the build fails.
    """
    full_tag = f"{image_name}:{image_tag}"
    logger.info(f"Building Docker image '{full_tag}' from {build_path}")

    from src.config.settings import settings
    import sys
    if getattr(settings, "SIMULATE_DOCKER", False) and "pytest" not in sys.modules:
        logger.info(f"[SIMULATION] Mocking Docker build for image: {full_tag}")
        return BuildResult(
            success=True,
            image_id="sha256-mock-image-id-123456789",
            image_name=image_name,
            image_tag=image_tag,
            size_bytes=150000000,
            build_logs=[
                "Step 1/5 : FROM python:3.11-slim",
                " ---> Using cache",
                "Step 2/5 : WORKDIR /app",
                " ---> Using cache",
                "Step 3/5 : COPY requirements.txt .",
                " ---> Using cache",
                "Step 4/5 : RUN pip install --no-cache-dir -r requirements.txt",
                " ---> [SIMULATION] Simulated pip install completed successfully",
                "Step 5/5 : COPY . .",
                "Successfully built sha256-mock-image-id-123456789",
                "Successfully tagged " + full_tag
            ]
        )

    if not is_docker_available():
        logger.warning("Docker daemon not available. Cannot build image.")
        return BuildResult(
            success=False,
            image_name=image_name,
            image_tag=image_tag,
            error_message="Docker daemon is not available. Is Docker Desktop running?",
        )

    build_context = Path(build_path).resolve()
    if not build_context.exists():
        raise DockerException(
            f"Build context directory does not exist: {build_context}",
            details={"build_path": str(build_context)},
        )

    dockerfile_abs = build_context / dockerfile_path
    if not dockerfile_abs.exists():
        raise DockerException(
            f"Dockerfile not found at: {dockerfile_abs}",
            details={"dockerfile_path": str(dockerfile_abs)},
        )

    try:
        client = get_client()
        build_logs: List[str] = []

        # Build with streaming logs
        image, log_generator = client.images.build(
            path=str(build_context),
            dockerfile=dockerfile_path,
            tag=full_tag,
            rm=True,           # Remove intermediate containers
            forcerm=True,      # Force remove on failure
            pull=False,        # Don't pull base image every time
        )

        # Collect build log lines
        for chunk in log_generator:
            if "stream" in chunk:
                line = chunk["stream"].strip()
                if line:
                    build_logs.append(line)
                    logger.debug(f"[build] {line}")
            elif "error" in chunk:
                error_msg = chunk["error"].strip()
                build_logs.append(f"ERROR: {error_msg}")
                logger.error(f"[build error] {error_msg}")

        # Get image metadata
        image.reload()
        size_bytes = image.attrs.get("Size", 0)
        image_id = image.id

        logger.info(
            f"Image '{full_tag}' built successfully. "
            f"ID: {image_id[:19]}, Size: {size_bytes / (1024*1024):.1f} MB"
        )

        return BuildResult(
            success=True,
            image_id=image_id,
            image_name=image_name,
            image_tag=image_tag,
            size_bytes=size_bytes,
            build_logs=build_logs[-50:],  # Keep last 50 lines
        )

    except Exception as e:
        logger.error(f"Docker image build failed for '{full_tag}': {e}", exc_info=True)
        return BuildResult(
            success=False,
            image_name=image_name,
            image_tag=image_tag,
            error_message=str(e),
            build_logs=[f"Build failed: {e}"],
        )


def list_images(name_filter: Optional[str] = None) -> List[Dict[str, Any]]:
    """Lists Docker images, optionally filtered by name prefix.

    Args:
        name_filter: Optional image name prefix to filter results (e.g., 'apexdeploy/').

    Returns:
        List of dicts with image metadata (id, tags, size, created).
    """
    if not is_docker_available():
        return []

    try:
        client = get_client()
        kwargs = {}
        if name_filter:
            kwargs["name"] = name_filter

        images = client.images.list(**kwargs)

        result = []
        for img in images:
            result.append({
                "id": img.short_id,
                "tags": img.tags,
                "size_bytes": img.attrs.get("Size", 0),
                "created": img.attrs.get("Created", ""),
            })

        return result

    except Exception as e:
        logger.warning(f"Failed to list Docker images: {e}")
        return []


def remove_image(image_name_or_id: str, force: bool = False) -> bool:
    """Removes a Docker image by name or ID.

    Args:
        image_name_or_id: Image name (with tag) or ID.
        force: Force removal even if containers are using the image.

    Returns:
        True if successfully removed, False otherwise.
    """
    if not is_docker_available():
        return False

    try:
        client = get_client()
        client.images.remove(image=image_name_or_id, force=force)
        logger.info(f"Removed Docker image: {image_name_or_id}")
        return True
    except Exception as e:
        logger.warning(f"Failed to remove image '{image_name_or_id}': {e}")
        return False
